# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/kowareta/workspace/A.M/1/project_1/project_1.srcs/sources_1/ip/ddr_controller_0/ddr_controller_0.xci
# IP: The module: 'ddr_controller_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/kowareta/workspace/A.M/1/project_1/project_1.gen/sources_1/ip/ddr_controller_0/project_1.srcs/sources_1/ip/mig_7series_0/mig_7series_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mig_7series_0 || ORIG_REF_NAME==mig_7series_0} -quiet] -quiet

# XDC: /home/kowareta/workspace/A.M/1/project_1/project_1.gen/sources_1/ip/ddr_controller_0/project_1.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mig_7series_0 || ORIG_REF_NAME==mig_7series_0} -quiet] -quiet

# XDC: /home/kowareta/workspace/A.M/1/project_1/project_1.gen/sources_1/ip/ddr_controller_0/project_1.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0_ooc.xdc

# IP: /home/kowareta/workspace/A.M/1/project_1/project_1.srcs/sources_1/ip/ddr_controller_0/ddr_controller_0.xci
# IP: The module: 'ddr_controller_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/kowareta/workspace/A.M/1/project_1/project_1.gen/sources_1/ip/ddr_controller_0/project_1.srcs/sources_1/ip/mig_7series_0/mig_7series_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mig_7series_0 || ORIG_REF_NAME==mig_7series_0} -quiet] -quiet

# XDC: /home/kowareta/workspace/A.M/1/project_1/project_1.gen/sources_1/ip/ddr_controller_0/project_1.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mig_7series_0 || ORIG_REF_NAME==mig_7series_0} -quiet] -quiet

# XDC: /home/kowareta/workspace/A.M/1/project_1/project_1.gen/sources_1/ip/ddr_controller_0/project_1.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0_ooc.xdc
